DROP TABLE IF EXISTS PARTICIPANT;

CREATE TABLE "PARTICIPANT"(
    "ID" VARCHAR2(6) NOT NULL PRIMARY KEY,
    "NAME_PARTICIPANT" VARCHAR2(48) NOT NULL,
    "AGE" NUMBER,
    "DESCRIPTION" VARCHAR2(100) NOT NULL
);